// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Enum_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Enum_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Enum_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

enum ObjectType : int {
  OBJECT_TYPE_NONE = 0,
  OBJECT_TYPE_CREATURE = 1,
  OBJECT_TYPE_PROJECTILE = 2,
  OBJECT_TYPE_ENV = 3,
  OBJECT_TYPE_BAG = 4,
  ObjectType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ObjectType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ObjectType_IsValid(int value);
constexpr ObjectType ObjectType_MIN = OBJECT_TYPE_NONE;
constexpr ObjectType ObjectType_MAX = OBJECT_TYPE_BAG;
constexpr int ObjectType_ARRAYSIZE = ObjectType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ObjectType_descriptor();
template<typename T>
inline const std::string& ObjectType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ObjectType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ObjectType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ObjectType_descriptor(), enum_t_value);
}
inline bool ObjectType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ObjectType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ObjectType>(
    ObjectType_descriptor(), name, value);
}
enum CreatureType : int {
  CREATE_TYPE_NONE = 0,
  CREATE_TYPE_PLAYER = 1,
  CREATE_TYPE_MONSTER = 2,
  CREATE_TYPE_NPC = 3,
  CreatureType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  CreatureType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool CreatureType_IsValid(int value);
constexpr CreatureType CreatureType_MIN = CREATE_TYPE_NONE;
constexpr CreatureType CreatureType_MAX = CREATE_TYPE_NPC;
constexpr int CreatureType_ARRAYSIZE = CreatureType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CreatureType_descriptor();
template<typename T>
inline const std::string& CreatureType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, CreatureType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function CreatureType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    CreatureType_descriptor(), enum_t_value);
}
inline bool CreatureType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, CreatureType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<CreatureType>(
    CreatureType_descriptor(), name, value);
}
enum PlayerType : int {
  PLAYER_TYPE_NONE = 0,
  PLAYER_TYPE_KNIGHT = 1,
  PLAYER_TYPE_MAGE = 2,
  PLAYER_TYPE_ARCHER = 3,
  PlayerType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  PlayerType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool PlayerType_IsValid(int value);
constexpr PlayerType PlayerType_MIN = PLAYER_TYPE_NONE;
constexpr PlayerType PlayerType_MAX = PLAYER_TYPE_ARCHER;
constexpr int PlayerType_ARRAYSIZE = PlayerType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PlayerType_descriptor();
template<typename T>
inline const std::string& PlayerType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PlayerType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PlayerType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PlayerType_descriptor(), enum_t_value);
}
inline bool PlayerType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PlayerType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PlayerType>(
    PlayerType_descriptor(), name, value);
}
enum MoveState : int {
  MOVE_STATE_NONE = 0,
  MOVE_STATE_IDLE = 1,
  MOVE_STATE_RUN = 2,
  MOVE_STATE_SKILL = 3,
  MoveState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MoveState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MoveState_IsValid(int value);
constexpr MoveState MoveState_MIN = MOVE_STATE_NONE;
constexpr MoveState MoveState_MAX = MOVE_STATE_SKILL;
constexpr int MoveState_ARRAYSIZE = MoveState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MoveState_descriptor();
template<typename T>
inline const std::string& MoveState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MoveState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MoveState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MoveState_descriptor(), enum_t_value);
}
inline bool MoveState_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MoveState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MoveState>(
    MoveState_descriptor(), name, value);
}
enum DamageType : int {
  DAMAGE_TYPE_PHYSICAL = 0,
  DAMAGE_TYPE_MAGIC = 1,
  DamageType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  DamageType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool DamageType_IsValid(int value);
constexpr DamageType DamageType_MIN = DAMAGE_TYPE_PHYSICAL;
constexpr DamageType DamageType_MAX = DAMAGE_TYPE_MAGIC;
constexpr int DamageType_ARRAYSIZE = DamageType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DamageType_descriptor();
template<typename T>
inline const std::string& DamageType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DamageType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DamageType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DamageType_descriptor(), enum_t_value);
}
inline bool DamageType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DamageType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DamageType>(
    DamageType_descriptor(), name, value);
}
enum CcType : int {
  CC_TYPE_NONE = 0,
  CC_TYPE_STUN = 1,
  CC_TYPE_ROOT = 2,
  CC_TYPE_KNOCKBACK = 4,
  CC_TYPE_LAUNCH = 8,
  CC_TYPE_SLOW = 16,
  CC_TYPE_HEAL_REDUCTION = 32,
  CC_TYPE_SILENCE = 64,
  CcType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  CcType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool CcType_IsValid(int value);
constexpr CcType CcType_MIN = CC_TYPE_NONE;
constexpr CcType CcType_MAX = CC_TYPE_SILENCE;
constexpr int CcType_ARRAYSIZE = CcType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CcType_descriptor();
template<typename T>
inline const std::string& CcType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, CcType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function CcType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    CcType_descriptor(), enum_t_value);
}
inline bool CcType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, CcType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<CcType>(
    CcType_descriptor(), name, value);
}
enum DeathCause : int {
  DEATH_CAUSE_NONE = 0,
  DEATH_CAUSE_PLAYER = 1,
  DEATH_CAUSE_MONSTER = 2,
  DeathCause_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  DeathCause_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool DeathCause_IsValid(int value);
constexpr DeathCause DeathCause_MIN = DEATH_CAUSE_NONE;
constexpr DeathCause DeathCause_MAX = DEATH_CAUSE_MONSTER;
constexpr int DeathCause_ARRAYSIZE = DeathCause_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DeathCause_descriptor();
template<typename T>
inline const std::string& DeathCause_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DeathCause>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DeathCause_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DeathCause_descriptor(), enum_t_value);
}
inline bool DeathCause_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DeathCause* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DeathCause>(
    DeathCause_descriptor(), name, value);
}
enum EquipSlot : int {
  SLOT_NONE = 0,
  SLOT_WEAPON_PRIMARY = 1,
  SLOT_WEAPON_SECONDARY = 2,
  SLOT_HELMET = 3,
  SLOT_ARMOR = 4,
  SLOT_BOOTS = 5,
  SLOT_TRINKET = 6,
  EquipSlot_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  EquipSlot_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool EquipSlot_IsValid(int value);
constexpr EquipSlot EquipSlot_MIN = SLOT_NONE;
constexpr EquipSlot EquipSlot_MAX = SLOT_TRINKET;
constexpr int EquipSlot_ARRAYSIZE = EquipSlot_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EquipSlot_descriptor();
template<typename T>
inline const std::string& EquipSlot_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EquipSlot>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EquipSlot_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EquipSlot_descriptor(), enum_t_value);
}
inline bool EquipSlot_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EquipSlot* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EquipSlot>(
    EquipSlot_descriptor(), name, value);
}
enum SlotBindState : int {
  BIND_UNBOUND = 0,
  BIND_BOUND = 1,
  BIND_SHADOWED = 2,
  SlotBindState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  SlotBindState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool SlotBindState_IsValid(int value);
constexpr SlotBindState SlotBindState_MIN = BIND_UNBOUND;
constexpr SlotBindState SlotBindState_MAX = BIND_SHADOWED;
constexpr int SlotBindState_ARRAYSIZE = SlotBindState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SlotBindState_descriptor();
template<typename T>
inline const std::string& SlotBindState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, SlotBindState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function SlotBindState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    SlotBindState_descriptor(), enum_t_value);
}
inline bool SlotBindState_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, SlotBindState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<SlotBindState>(
    SlotBindState_descriptor(), name, value);
}
enum GrantResult : int {
  GRANT_OK = 0,
  GRANT_ALREADY = 1,
  GRANT_NO_TARGET = 2,
  GRANT_DB_ERROR = 3,
  GRANT_BAD_REQUEST = 4,
  GrantResult_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  GrantResult_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool GrantResult_IsValid(int value);
constexpr GrantResult GrantResult_MIN = GRANT_OK;
constexpr GrantResult GrantResult_MAX = GRANT_BAD_REQUEST;
constexpr int GrantResult_ARRAYSIZE = GrantResult_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GrantResult_descriptor();
template<typename T>
inline const std::string& GrantResult_Name(T enum_t_value) {
  static_assert(::std::is_same<T, GrantResult>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function GrantResult_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    GrantResult_descriptor(), enum_t_value);
}
inline bool GrantResult_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, GrantResult* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<GrantResult>(
    GrantResult_descriptor(), name, value);
}
enum ItemGrade : int {
  ITEM_GRADE_NONE = 0,
  ITEM_GRADE_COMMON = 1,
  ITEM_GRADE_RARE = 2,
  ITEM_GRADE_EPIC = 3,
  ITEM_GRADE_LEGENDARY = 4,
  ItemGrade_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ItemGrade_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ItemGrade_IsValid(int value);
constexpr ItemGrade ItemGrade_MIN = ITEM_GRADE_NONE;
constexpr ItemGrade ItemGrade_MAX = ITEM_GRADE_LEGENDARY;
constexpr int ItemGrade_ARRAYSIZE = ItemGrade_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ItemGrade_descriptor();
template<typename T>
inline const std::string& ItemGrade_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ItemGrade>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ItemGrade_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ItemGrade_descriptor(), enum_t_value);
}
inline bool ItemGrade_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ItemGrade* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ItemGrade>(
    ItemGrade_descriptor(), name, value);
}
enum ItemState : int {
  ITEM_STATE_NONE = 0,
  ITEM_STATE_CARRIED = 1,
  ITEM_STATE_EQUIPPED = 2,
  ITEM_STATE_VAULTED = 3,
  ITEM_STATE_IN_BAG = 4,
  ItemState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ItemState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ItemState_IsValid(int value);
constexpr ItemState ItemState_MIN = ITEM_STATE_NONE;
constexpr ItemState ItemState_MAX = ITEM_STATE_IN_BAG;
constexpr int ItemState_ARRAYSIZE = ItemState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ItemState_descriptor();
template<typename T>
inline const std::string& ItemState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ItemState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ItemState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ItemState_descriptor(), enum_t_value);
}
inline bool ItemState_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ItemState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ItemState>(
    ItemState_descriptor(), name, value);
}
enum ItemResult : int {
  ITEM_OK = 0,
  ITEM_ALREADY = 1,
  ITEM_NOT_FOUND = 2,
  ITEM_INVALID_STATE = 3,
  ITEM_INVENTORY_FULL = 4,
  ITEM_BAD_REQUEST = 5,
  ITEM_DB_ERROR = 6,
  ItemResult_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ItemResult_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ItemResult_IsValid(int value);
constexpr ItemResult ItemResult_MIN = ITEM_OK;
constexpr ItemResult ItemResult_MAX = ITEM_DB_ERROR;
constexpr int ItemResult_ARRAYSIZE = ItemResult_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ItemResult_descriptor();
template<typename T>
inline const std::string& ItemResult_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ItemResult>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ItemResult_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ItemResult_descriptor(), enum_t_value);
}
inline bool ItemResult_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ItemResult* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ItemResult>(
    ItemResult_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Protocol::ObjectType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ObjectType>() {
  return ::Protocol::ObjectType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::CreatureType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::CreatureType>() {
  return ::Protocol::CreatureType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::PlayerType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::PlayerType>() {
  return ::Protocol::PlayerType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::MoveState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::MoveState>() {
  return ::Protocol::MoveState_descriptor();
}
template <> struct is_proto_enum< ::Protocol::DamageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::DamageType>() {
  return ::Protocol::DamageType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::CcType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::CcType>() {
  return ::Protocol::CcType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::DeathCause> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::DeathCause>() {
  return ::Protocol::DeathCause_descriptor();
}
template <> struct is_proto_enum< ::Protocol::EquipSlot> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::EquipSlot>() {
  return ::Protocol::EquipSlot_descriptor();
}
template <> struct is_proto_enum< ::Protocol::SlotBindState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::SlotBindState>() {
  return ::Protocol::SlotBindState_descriptor();
}
template <> struct is_proto_enum< ::Protocol::GrantResult> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::GrantResult>() {
  return ::Protocol::GrantResult_descriptor();
}
template <> struct is_proto_enum< ::Protocol::ItemGrade> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ItemGrade>() {
  return ::Protocol::ItemGrade_descriptor();
}
template <> struct is_proto_enum< ::Protocol::ItemState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ItemState>() {
  return ::Protocol::ItemState_descriptor();
}
template <> struct is_proto_enum< ::Protocol::ItemResult> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ItemResult>() {
  return ::Protocol::ItemResult_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
